name: PyPi

on:
  push:
    tags: ['*']
  # Won't work with the above, it'll be and/or
  # workflow_run:
  #   workflows: ["pytest"]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  build-n-publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt
        pip install -r requirements.txt
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Check for beta tag
      id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+[a|b]{1}[0-9]+$ ]]; then
            echo ::set-output name=beta::true
        fi
    - name: Push to Test PyPi
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Push to PyPi
      if: startsWith(github.ref, 'refs/tags/v') && steps.check-tag.outputs.beta != 'true'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
